docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - 'Quick Start': quick-start.md
    - Reference:
      - 'Configuring the service manager': configuring-the-service-manager.md
      - Delegators: delegators.md
      - 'Lazy services': lazy-services.md
      - 'Plugin managers': plugin-managers.md
    - 'Migration Guide': migration.md
site_name: laminas-servicemanager
site_description: 'laminas-servicemanager: factory-driven dependency injection container'
repo_url: 'https://github.com/laminas/laminas-servicemanager'
